run-usefull_chars: build-usefull_chars
	./target/usefull_chars.out

build-usefull_chars:
	mkdir -p target
	g++ ./usefull_chars.cpp -o target/usefull_chars.out


run-string_objects: build-string_objects
	mkdir -p target
	./target/string_objects.out

build-string_objects:
	mkdir -p target
	g++ ./string_objects.cpp -o target/string_objects.out
